### ISSUE TITLE
Cut from CoundQt editor to Windows clipboard and paste into external editor does not work

### ISSUE THREAD

**Issue by gogins** [CsoundQt/CsoundQt#223] opened 2017-01-05 00:34 UTC

**Comment by tarmoj** [comment] 2017-04-11 07:30
Cannot reproduce - works here (Windows 7 professional) - both with installed version and built from git with msys2/mingw compiler. I will try to test on other Windows machines as well.

**Comment by gogins** [comment] 2017-04-11 10:03
My experience is that it worked at times but not at other times.

Best,
Mike

**Comment by tarmoj** [comment] 2017-04-11 12:44
Indeed, it seems to fail when clipboard is already opened by another progra,. The error message from CsoundQt is:
OleSetClipboard: Failed to set mime data (text/plain, text/html, application/vnd.oasis.opendocument.text) on clipboard:
And one first form post about this (although not exactyl helping):'
https://bugreports.qt.io/browse/QTBUG-27097

I will investigate further later.

**Comment by gogins** [comment] 2017-04-11 21:01
That's what I saw and your info should be very helpful.

Best,
Mike

**Comment by mantaraya36** [comment] 2017-04-12 17:43
I seem to remember that a similar issue was caused by FLTK. Just the fact
that the fltk plugins are loaded used to cause a similar issue. Can you try
moving all fltk stuff out of the way and testing to see if clipboard works?

(You need to move fluidsynth stuff too)

**Comment by tarmoj** [comment] 2017-04-13 15:57
Thanks, Andres, it was a helping hint -  I made experiments and indeed, the problem disappeared when I moved wigets.dll and virtual.dll away from plugins64 in Csound installation directory. Michael, please try, if it helps you also.

Might be that the fltk opcodes open the clipboard in some way or there is a hidden race condition for clipboard it or there is some other problem.

Unfortunately I don't see any way how to solve it from CsoundQt's side: I tried to override TextEdit's copy() and paste() method but it did not help since the error happens in system before the performance queue arrives to QTextedit.

So for now it is something we take as "known issue" and see if it is different with Csound 6.09. 

Michael, do you have any chance to try it out with latest Csound build?

**Comment by gogins** [comment] 2017-04-13 18:48
Thanks for looking at this. Yes I will rebuild and test. I will look into
the FLTK stuff.

Best,
Mike

**Comment by gogins** [comment] 2017-05-06 15:13
I found is a partial workaround. Drag and drop works fine to copy and paste from an external editor to the CsoundQt main editor, but not always to copy and paste from the CsoundQt main editor to an external editor.

**Comment by tarmoj** [comment] 2017-07-04 18:59
Fixed with commit 5bb1567363f (develop branch)

**Closed by tarmoj** 2017-07-04 18:59 UTC
Labels: bug
