### ISSUE TITLE
Widgets' problems in Mac OS Catalina 10.15.5

### ISSUE THREAD

**Issue by Luissssss** [CsoundQt/CsoundQt#332] opened 2020-07-20 09:54 UTC
Hi everybody! I'm using the latest version of Csound QT (9.8.1), and I've just noticed that the _spin box_ widget doesn't show the background color! It remains white. No problem for the text color.
Another issue that I've found is with the _scope_ widget: it doesn't show the waveform properly (for example with granular synthesis: a single grain with a smooth amplitude envelope sounds good but the waveform is shown truncated and repeated, as i should expected to hear clicks and a longer sound event). Thanks a lot for the support, best regards
Luis
<img width="854" alt="Schermata 2020-07-10 alle 18 56 40" src="https://user-images.githubusercontent.com/17232722/87924494-4675bd00-ca7f-11ea-9aef-92f5245da2da.png">
<img width="866" alt="Schermata 2020-07-20 alle 11 53 27" src="https://user-images.githubusercontent.com/17232722/87924875-c9971300-ca7f-11ea-817b-8362be1d13ce.png">

**Comment by gesellkammer** [comment] 2020-07-20 15:00
The spinbox is drawn natively and on macos the background can't be themed. Use a scrollnumber widget instead.
Regarding scope, this is fixed in git, where scope gained a triggered mode.

**Comment by Luissssss** [comment] 2020-07-20 16:22
Hi, the spin box on my last Mac OS was working good, themed as well! I
don’t know why now it doesn’t work anymore!
And for the scope, i don’t understand? Where is fixed? Should I download a
latest version?
Regards
Luis

Il giorno lun 20 lug 2020 alle 17:01 Eduardo Moguillansky <
notifications@github.com> ha scritto:

**Comment by Luissssss** [comment] 2020-07-25 08:02
Excuse me??

Il giorno lun 20 lug 2020 alle 18:22 Luis Braschi <braschi.luis@gmail.com>
ha scritto:

**Comment by tarmoj** [comment] 2020-07-28 15:12
Hi,


About the spinbox background:

I investigated this and the problem is that in current version of CsoundQt on MacOS CsoundQt is forced to use the light Aqua theme (field NSRequiresAquaSystemAppearance in Info.plist of the app) and somehow this takes control over Qt spinboxes completely and I did not find a way how to counter-control it from the code.

The strange thing is that if to switch system to Dark mode and change NSRequiresAquaSystemAppearance to False, the spinbox can be styled but the overall look of CsoundQt is very off.

I have done some work for the dark mode support but it is nod finished and this build does not have the latest commits from in the develop branch:

see: https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.8-rc3

I wonder -  you said "spin box on my last Mac OS was working good, themed as well" I wonder which version of MacOS and CsoundQt it was? I got the same results (ie spinbox not styled) with CsoundQt 0.9.7 and 0.9.6-2 on Mojave.


2) Eduardo commited the changes of scope widget to the source code in git. We will make next bugfix release when there will be enough to publish, hopefully soon.

Greetings,
tarmo

**Comment by Luissssss** [comment] 2020-07-28 16:08
Hi,
unfortunately I don't remember the exact Csound version that I was using,
with the spin box working fine, but the OS was High Sierra. Anyway, thanks
for the info about scope widget, now I've understood. I'll update Csound as
soon as it will be available! Hope that maybe you'll be able to fix the
spin box's bug too! I'll use the scroll number widget in the meantime!
thank you all, best regards
Luis

Il giorno mar 28 lug 2020 alle ore 17:13 Tarmo Johannes <
notifications@github.com> ha scritto:

**Comment by tarmoj** [comment] 2020-07-28 16:41
HI,

If the system was High Sierra, it makes sense - Apple introduced the theme business from Mojave. I am afraid there is not much to do from our side, I can try later to build with Qt 5.15  (version 5.12 is used now), but not sure if gives any other result. 

tarmo

**Closed by tarmoj** 2020-07-28 16:41 UTC
