### ISSUE TITLE
Audio / MIDI Test not working for stereo

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#308] opened 2020-05-30 08:35 UTC
when i use portaudio, the "Audio / MIDI Test" (activated by Configure>Run>Test Audio Setup) returns an error is using the internal audio card:
   Invalid number of channels
because nchnls=8 is set in the .csd.

this is CsoundQt 0.9.8-rc3 on OSX 10.15 (Csound 6.14).
same error occurs under linux with pulse audio.
(it works with jack.)

solution might be to set the nchnls dynamically, depending on the detected hardware setup?

**Comment by tarmoj** [comment] 2020-06-06 10:05
Hi,

Yes, I have experienced same thing with portaudio and pulse. 

But I think it is not problem of CsoundQt -  pulseaudio/portaudio cannot work if the nchnls is not matching with the actual number of hardware channels (you are correct). I think there is no way to know  how many actual hardware channels there are inside of csd and I am not sure if the system starts to set the channels, it  may override what a user actually wants in other csds  

Luckily you can be set correct number of channels  from the new option in Configure->Run: check "Channels" and set the spinbox to the correct number, then the TestAudio should work

Or can you describe more exactly what did you mean with the "set the nchnls dynamically"?

I agree, that it can be confusing and at least some kind of warning would be helpful. I am not sure yet where and how this check should happen, though. ConfigDialog::testAudioSetup() maybe?

tarmo

**Comment by gesellkammer** [comment] 2020-06-16 15:26
I can't reproduce this with portaudio. I see a rate mismatch when using system sample rate (maybe system sr should be disabled in portaudio also) but no problems with channels. 
Regarding setting number of channels dynamically, I don't know what that means exactly, but I assume something like using "nchnls_hw" in the csd. But this does not work, because nchnls_hw is actually garbage and should be fixed or removed. 
To sort of solve this is that the settings dialog lets you set the number of channels, so the nchnls=8 inside the csd will be overriden.

**Closed** 2020-06-16 15:29 UTC
