### ISSUE TITLE
After installing CsoundQt, the keyboard shortcuts doesn't work.

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#286] opened 2019-08-18 16:09 UTC
Its is also the case after Help/Reset Preferences.

To work normally I had to go to the Edit menu, select "Set Keyboard Shortcuts" and select "Restore Defaults".

There is the same behaviour on Mac OS X and Windows.

**Comment by tarmoj** [comment] 2019-08-20 08:19
Thanks or the report!
Is it so that it happens when you do a "clean install" -  ie no CsoundQt and its preferences was in the computer before or is there was a previous version beforehand?

tarmo

**Comment by bernardgeyer** [comment] 2019-08-20 13:07
It happend the first time I installed CsoundQt and a collegue with which I
work had the same problem.

Le mar. 20 août 2019 à 10:19, Tarmo Johannes <notifications@github.com> a
écrit :

**Comment by joachimheintz** [comment] 2019-08-24 20:23
i just installed csound and csoundqt on a new mac (mojave).  shortcuts 
were working out of the box.  what is not working at all are the 
shortcuts for tabs (we can live with it in the studio).

i see two main issues currently on osx:
1) we are forced to use jack; otherwise the latency is ridiculous.  for 
me and my students it is ok, but it is very unlucky that we cannot find 
out the reason.  the normal user will say: oh csound is bad.
2) the resolution of the main csoundqt window does not stay as it was in 
the previous session (rather it is much too small).  this is a minor 
issue in a way, but nevertheless ugly.

these were the versions i used:
csound: 
https://github.com/csound/csound/releases/download/6.13.0/Csound6.13.0-MacOS_x86_64.dmg
csoundqt: 
https://github.com/CsoundQt/CsoundQt/releases/download/0.9.6/CsoundQt-0.9.6-pythonqt-MacOS.dmg

sorry for messing up this thread with other subjects ...

**Comment by tarmoj** [comment] 2019-11-27 08:48
The window size restoring is fixed now in v0.9.7-beta, cannot reproduce shortcuts problem, though.

**Closed by tarmoj** 2019-11-27 08:48 UTC
