### ISSUE TITLE
Problem with rtmidi

### ISSUE THREAD

**Issue by ReneDjack** [CsoundQt/CsoundQt#211] opened 2016-06-09 10:10 UTC
Hi,
I have the following problem when i play with external midi KB :

csoundqt crash if i open a csd and then play one midi note on external KB.

My setup is MIDI input interface = USB Axiom 49 24:0 (external midi KB) using rtmidi version 2.1.1,
csoundqt version 0.9.2.1 on Linux.

My trick is, i open the csd, i select my midi KB in the setup then i close csoundqt,
then i open csoundqt and now i can play for hours... (on the opened csd)

Regards, René

**Comment by tarmoj** [comment] 2016-06-09 10:28
Can you send some more information -
do you have any error messaged on the crash? (Say if you start csoundqt in
terminal)
What audio driver are you using - portaudio/alsa/jack? (Probably
irrelevant...)
I guess you use the CsoundQt internal midi system (rtmidi), not csound midi
modules?
If it works all right after setting correct device in options and
restarting CsoundQt, there could be a bug how CsoundQt remembers the midi
device indexes or restores them wrong or turns to nonexisting devices.
I cannot test it myself for some days, but if you can ivestigate the logic
of conditions when the error happens, is great help. If possible, try to
plug in different devices in different combinations and see if you can
detect the reason.
Thanks!
Tamo
09.06.2016 13:11 kirjutas kuupäeval "ReneDjack" <notifications@github.com>:

**Comment by ReneDjack** [comment] 2016-06-09 17:37
Hi Tarmo,

Thanks for reading me, here my tests

No problem when using Csound modules with -Ma flag
No problem when using the virtual midi KB
No problem when using Csound alone with -Ma flag


Problem is only when using rtmidi in Csoundqt.


Following is the console output with my comments


** MY USB KB IS ON

** I START CSOUNDQT

   moi@Linux ~/Programmes/Scripts $ ./csoundqt.sh
   Loading Csound preferences...Using csound double
   virtual_keyboard real time MIDI plugin for Csound
   0dBFS level = 32768,0
   Csound version 6.07 (double samples) May 19 2016
   libsndfile-1.0.25
   end of score.           overall amps:      0,0
        overall samples out of range:        0
   0 errors in performance
   Elapsed time at end of performance: real: 0,000s, CPU: 0,000s
   QObject::connect: No such slot WidgetPanel::dockStateChanged(bool)
   Warning: Could not find FLOSS Manual Examples.
   Warning: Could not find McCurdy Collection.
   Warning: Could not find Stria Synth files.
   QObject::connect: No such signal FileBEditor::textChanged()
   QObject::connect:  (sender name:   'FileBEditor')
   QObject::connect: No such signal FileBEditor::textChanged()
   QObject::connect:  (sender name:   'FileBEditor')
   QObject::connect: No such slot DocumentPage::evaluate(QString)
   WidgetLayout::loadXmlWidgets Older Widget Format version

** CSOUNDQT IS STARTED
     OPENNED FILE IS DX7_Mooger.csd (saved in previous cession)
     CONFIGURE/REALTIME MIDI/MIDI input interface is USB Axiom 49 24:0 
(saved in previous cession)
     Csound MIDI modules (unstable) not used
     RT Audio Module is alsa

** I HIT RUN BUTTON

     CsoundQt::play()...
     virtual_keyboard real time MIDI plugin for Csound
     0dBFS level = 32768,0
     Csound version 6.07 (double samples) May 19 2016
     libsndfile-1.0.25
     csound
     -b32
     -B4096
     -+rtaudio=alsa
     -odac
     --env:CSNOSTOP=yes
     /home/moi/Works/0_Csound_EnCours/DX7/DX7_Mooger.csd

** I CAN PLAY FROM MIDI WITHOUT PROBLEM

** I HIT THE STOP BUTTON

     CsoundQt::stop()  -1
     Recording stopped.
     CsoundEngine::stopCsound() joined

** I OPEN A SECOND FILE (DX7_Oberheim.csd)

     QObject::connect: No such signal FileBEditor::textChanged()
     QObject::connect:  (sender name:   'FileBEditor')
     QObject::connect: No such slot DocumentPage::evaluate(QString)
     WidgetLayout::loadXmlWidgets Older Widget Format version

** I HIT THE RUN BUTTON

     CsoundQt::play()...
     virtual_keyboard real time MIDI plugin for Csound
     0dBFS level = 32768.0
     Csound version 6.07 (double samples) May 19 2016
     libsndfile-1.0.25
     csound
     -b32
     -B4096
     -+rtaudio=alsa
     -odac
     --env:CSNOSTOP=yes
     /home/moi/Works/0_Csound_EnCours/DX7/DX7_Oberheim.csd

** I CAN PLAY FROM MIDI WITHOUT PROBLEM

** I HIT THE STOP BUTTON

     CsoundQt::stop()  -1
     Recording stopped.
     CsoundEngine::stopCsound() joined

** AT THIS STAGE I CAN RUN / STOP AND PLAY WITH MIDI THE FIRST OR THE 
SECOND FILE.

** THE PROBLEM ARISE WHEN

** I CLOSE THE FIRST FILE (DX7_Mooger.csd)

     Recording stopped.
     Recording stopped.

** I HIT THE RUN BUTTON (to play with DX7_Oberheim.csd)

     CsoundQt::play()...
     virtual_keyboard real time MIDI plugin for Csound
     0dBFS level = 32768.0
     Csound version 6.07 (double samples) May 19 2016
     libsndfile-1.0.25
     csound
     -b32
     -B4096
     -+rtaudio=alsa
     -odac
     --env:CSNOSTOP=yes
     /home/moi/Works/0_Csound_EnCours/DX7/DX7_Oberheim.csd

** I HIT A MIDI NOTE -> CSOUNDQT CRASHES

Csound tidy up: Erreur de segmentation
Csound tidy up: Erreur de segmentation
Csound tidy up: Erreur de segmentation
QObject::~QObject: Timers cannot be stopped from another thread
moi@Linux ~/Programmes/Scripts $


Hope this will help you
Regards,
René

**Comment by tarmoj** [comment] 2016-06-10 09:12
Thanks a lot for the detailed information!
I will get to it next week.
T
09.06.2016 20:37 kirjutas kuupäeval "ReneDjack" <notifications@github.com>:

**Comment by tarmoj** [comment] 2016-07-17 10:45
Hi Rene,
I have not forgotten but have not found time to tackle the bug I could
reproduce it and know more or less what can be the reason but have not
debugged it yet.
I woll be away for another two weeks, hopefully this jug does not stop your
work!
Thanks for reporting,
Tarmo

10.06.2016 12:12 kirjutas kuupäeval "Tarmo Johannes" <
tarmo.johannes@otsakool.edu.ee>:

Thanks a lot for the detailed information!
I will get to it next week.
T
09.06.2016 20:37 kirjutas kuupäeval "ReneDjack" <notifications@github.com>:

**Comment by ReneDjack** [comment] 2016-07-18 07:21
Hi Tarmo,

It is is not a critical bug, nothing urgent :)
Best,
René

**Comment by tarmoj** [comment] 2016-08-16 10:41
Hi,
I tracked down the reason - it was a small (well hidden) logical error in midihandler that did not delete midi listeners properly when a tab was closed.
Committed to git. Please test!
Thanks for the report, this error was hard to notice!
tarmo

**Closed by tarmoj** 2016-08-16 10:41 UTC

**Comment by ReneDjack** [comment] 2016-08-17 09:50
Hi Tarmo,

Tested, working fine :)

Thanks a lot

René
