### ISSUE TITLE
Copy / Paste not working

### ISSUE THREAD

**Issue by tmavuk** [CsoundQt/CsoundQt#239] opened 2017-06-27 04:32 UTC
I'm having a weird issue that copy / paste is not working on CsounQT 0.9.4. Both the shortcuts and manually clicking by the File menu seems to be not working. Thank you.

**Comment by tarmoj** [comment] 2017-06-27 07:39
Hi, this is a known issue and not completely solved yet. One work-around
that helped me -  if  try to move away widgets.dll and virtual.dll from you
Csound plugins directory (probably
C:\Program Files\Csound6_x64\plugins64 )
and restart CsoundQt.

These are FLTK plugins libraries, if you never need them, you will be fine.


The problem is that on Windows two programs cannot access clipboard exactly
on the same time and seems FLTK plugins are is doing it simultanuosly with
CsoundQt. Although not 100% sure.

Hope it helps!

tarmo


2017-06-27 7:32 GMT+03:00 Turgut Mavuk <notifications@github.com>:

**Comment by tarmoj** [comment] 2017-06-29 13:01
Hi,

I think I might have found and solved the issue! -

seems that there was probleem before in FLTK sources how it used clipboard
and Andres needed to introduce a workaround in the code of CsoundQt for
Windows. Now the bug has been fixed in FLTK sources and I needed to change
the code in CsoundQt  a bit. 

I uploaded a test-exe file to:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-d-cs6-clipboard-ok.zip

Unzip it and copy to C:\Program Files\Csound6_x64\bin and run from there.

Does it  work for you?

tarmo

**Comment by tmavuk** [comment] 2017-07-03 23:25
Hi Tarmo

Sorry for the late response, but this seems to be working fine. Thanks again for the help!!

**Comment by tarmoj** [comment] 2017-07-04 18:58
Great, glad to hear and thanks for feedback!

**Closed by tarmoj** 2017-07-04 18:58 UTC

**Comment by hectorC** [comment] 2020-04-08 02:26
CsoundQT version 0.9.7 (from Cssound 6.14.0 installer) on Windows 10. Cut and paste is not working. It cuts but pasting doesn't work and appears disabled in context menu.

**Comment by tarmoj** [comment] 2020-04-08 12:04
Hi, thanks for the report!

This was reported recently by another Windows user as well. I could not
reproduce and what helped was to completely remove Csound from Program
Files and reinstall Csound (and CsoundQt) -  with v 6.14 the installation
structure was changed considerably and might be that some old component
causes the problem.

Please try and report back!

tarmo

Kontakt Hector Centeno (<notifications@github.com>) kirjutas kuupäeval K,
8. aprill 2020 kell 05:26:
