### ISSUE TITLE
CsoundQT crash on exit - Windows

### ISSUE THREAD

**Issue by vlazzarini** [CsoundQt/CsoundQt#256] opened 2018-01-13 07:34 UTC
https://github.com/csound/csound/issues/913

**Comment by rorywalsh** [comment] 2018-01-13 09:38
Hi Tarmo, for what it's worth I'm not experiencing any crash on exit with my windows 10 laptop. I did try your current Windows release with the latest Windows installer but it didn't work for me. I think it might be an idea to produce a new build against the latest Windows Csound. If it works Ok I can package it together with Csound and replace the current installer, if Steven, Victor and John are Ok with that.

**Comment by vlazzarini** [comment] 2018-01-13 09:45
sounds like a good idea to me.

**Comment by vlazzarini** [comment] 2018-01-13 10:06
Once you’ve started building against the appveyor builds, we should modify the Appveyor script to pick your builds for packaging.
It’s better to make sure you have more control over what gets packaged.

**Comment by tarmoj** [comment] 2018-01-15 09:42
Hi,
I tried CsoundQt  from Windows installer from csound.com downloads and  the one from CsoundQt release page (zip file) -  both worked for me on two different computers running Windows 10. Rory, did you run the CsoundQt-release-page-CsoundQt from the unzipped folder? It cannot be copied to Csoundx64/bin or elsewhere.

The bad news is that I am still failing to build a working version of CsoundQt agains Csound 6.10 -  the build ends fine but I get crash whenever I start playback. I thought it is due to mismatch of libsndfile version of my build system and Csound, but I updated libsndfile andno difference.

Might be that this is due to compiler difference -  I have MSVSC 2015, Appveyor is using MSVC2017. I will Update when I will have time on the Windows machine again and try again to see if it makes any difference. 

tarmo

**Comment by rorywalsh** [comment] 2018-01-15 10:27
The current CsoundQT that ships with 6.10 will run for me, but the virtual
keyboard doesn't work as far as I can tell? The one from the CsoundQT page
didn't work for me with the latest .zip from the csoundqt github site but I
will try again and let you know.

**Comment by rorywalsh** [comment] 2018-01-15 15:38
Hi Tarmo, it looks like the version from your repo is now working fine for me. I'm going to see if I can bundle it with the current Csound release. What should the default directory be for the manual in CsoundQT? I will use the same location for Cabbage. My current default location for the manual on Windows is: 'C:\\Program Files\\Csound6_x64\\doc\\manual', what's CsoundQT's?

**Comment by tarmoj** [comment] 2018-01-15 19:50
Hi!

On esmaspäev, 15. jaanuar 2018 17:38.38 EET Rory Walsh wrote:
> Hi Tarmo, it looks like the version from your repo is now working fine for
> me.
Good to hear, thanks!
> 
> I'm going to see if I can bundle it with the current Csound release.
If it works it maybe makes sense, but it conflicts with the CsoundQt files included in the 
official installer (different Qt version for example) - ie both of them may not be in PATH or 
otherwise strange problems might start to happen.

I am still not sure what is the best way to deliver CsoundQt to Windows users. Felipe was 
working on the new installer system and if Core csound and frontends get separated but 
easily installable, it is naturally the best.

> What should the default directory be for the manual in CsoundQT? I will use
> the same location for Cabbage. My current default location for the manual
> on Windows is: 'C:\\Program Files\\Csound6_x64\\doc\\manual', what's
> CsoundQT's?
CsoundQt looks for manual from:
	initialDir = QCoreApplication::applicationDirPath();

        possibleDirectories << initialDir +"/doc/manual/" << programFilesPath + "/Csound6/doc/
manual/" << programFilesPathx86 + "/Csound6/doc/manual/" <<  programFilesPath + "/
Csound6_x64/doc/manual/";

Thus C:\\Program Files\\Csound6_x64\\doc\\manual is fine.
The latest Csound Windows installer unfortunately does not include the manual...

Thanks and let me know if you have any thoughts!

tarmo

**Comment by allforabit** [comment] 2018-05-01 12:00
I'm not sure if this is related to the same issue but I am unable to get the latest version of csound working on Windows 10. Similarly to Tarmo it all seems to work but crashes on attempted playback:
> The bad news is that I am still failing to build a working version of CsoundQt agains Csound 6.10 - the > build ends fine but I get crash whenever I start playback. I thought it is due to mismatch of libsndfile > version of my build system and Csound, but I updated libsndfile andno difference.

The previous version of csound worked fine but the latest version crashes whenever playback is attempted. The output from the command is as follows:
```
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.004s, CPU: 0.004s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.004s, CPU: 0.004s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 4096 sample-frame blocks
```
Apologies if this is the wrong issue to report my issue but the original issue that was reported on the csound repo was closed in favour of this one.

**Comment by tarmoj** [comment] 2018-05-01 13:16
Hi,  it might be some conflict with some earlier version.
Please try to dowload, unzip and run CsoundQt from here: 
https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.5

If it works, please try to do a clean reinstall of Csound (rename or remove existing directory) or always run CsoundQt from the unzipped folder.

Hope it helps!

tarmo

**Comment by allforabit** [comment] 2018-05-01 13:32
Thanks for that Tarmo, unfortunately it didn't work. I downloaded the package as instructed and opened it but go the same issue. I tried uninstalling csound and retried opening this package but when I do this it doesn't open the application at all and mentions that the `csound64` dll is missing. My main use will be for the commandline version of csound so maybe I should open a new issue on the main csound repo? I just want to be sure it's not a duplicate of this or the  issue here: https://github.com/csound/csound/issues/913

**Comment by rorywalsh** [comment] 2018-05-01 16:01
The version of CsoundQT that is bundled with the latest release of Csound for windows is working fine for me on my Windows 10 machine. Note that we tested it across a number of Windows 10 machines before releasing and didn't experience any issues. I do remember some issues at the start, but it has since been updated. I will do a clean install of this [Csound](https://github.com/csound/csound/releases/download/6.10.0/csound-windows-x64-6.10.0.exe) later on Win10 and see if I experience the same issues.

**Comment by rorywalsh** [comment] 2018-05-01 19:26
Just did a clean reinstall of Csound 6.10 and CsoundQT works right out of the box for me. I also checked on a few Windows 10 machines at works and had no issues. I think the problem may be local to you. I've had some issues in the past with conflicting versions of libsndfile.Do you have a libnsndfile dll in your System32 path? Or do you have any other software that uses libsndfile that be before Csound in the path env? @tarmoj I'm curious, why does CsoundQT have a libsndfile dependency?

**Comment by tarmoj** [comment] 2018-05-01 19:39
Thanks, Rory, for the report!

> @tarmoj I'm  curious, why does CsoundQT have a libsndfile dependency?

In fact: I have not found out myself so far -  I am not often developing on 
Windows and left it like that for now but I absolutely agree that it should 
not be necessary as csound64.dll has it linked in (if I am correct). Hope to 
work it out.

tarmo

**Comment by allforabit** [comment] 2018-05-01 19:48
Thanks very much for that Rory / Tarmoj. I will try to locate and remove the libnsndfile dll. I may have added it while building some other software project or other. I will report back to let you know how I get on.

**Comment by allforabit** [comment] 2018-05-02 10:42
I had libsndfile installed from http://www.mega-nerd.com installed. I uninstalled that and tried to make sure that there weren't any other versions in the path. Unfortunately it didn't seem to help and it still crashes both when I run it through csoundqt and on the commandline. It does render audio to a file but when I attempt to use a -odac it crashes. I will try a few things like using a different audio interface to see if I can get it working. Let me know if you have any pointers to how I'd go about debugging it to see the exact error message. Would I need to download the repo and build it?

**Comment by rorywalsh** [comment] 2018-05-02 10:54
So Csound is crashing from the command line when you try to output in
realtime? Have you tried -odac with different drivers? By default it uses
portaudio, maybe you can try winmme by running from the command line with
-+rtaudio=winmme, you might also try a different driver interface. To do so
pass -odac99 when running from the command line. That should fail, but give
you a list of interfaces to choose from. Might be good to post the output
of that here so we can take a look. The only option you have in terms of
debugging is to build Csound yourself. You'll need MSVC2017 and a fair
amount of hard disk space, but it's doable.

**Comment by allforabit** [comment] 2018-05-02 11:15
Here's the output for the first command using `-odac -+rtaudio=winmme`:
```
C:\Users\Admin\annex\areas\csound>csound -odac -+rtaudio=winmme hello-world\hello-world.csd
0dBFS level = 32768.0
--Csound version 6.10 (double samples) Jan 31 2018
[commit: f5bcd83a9799536980d0f674bb7525f45f800490]
libsndfile-1.0.29pre1
UnifiedCSD:  hello-world\hello-world.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.003s, CPU: 0.003s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.003s, CPU: 0.003s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 4096 sample-frame blocks
 unknown rtaudio module: 'winmme', using dummy module
rtaudio: dummy module enabled
writing 4096 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
B  0.000 .. 10.000 T 10.000 TT 10.000 M:   8192.0
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:   8192.0
           overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 9.946s, CPU: 9.946s
108 4096 sample blks of 64-bit floats written to dac
```

And attempting to use -odac99 gives me the same result as using -odac. It crashes more or less immediately and gives this output:
```
C:\Users\Admin\annex\areas\csound>csound -odac99 hello-world\hello-world.csd
0dBFS level = 32768.0
--Csound version 6.10 (double samples) Jan 31 2018
[commit: f5bcd83a9799536980d0f674bb7525f45f800490]
libsndfile-1.0.29pre1
UnifiedCSD:  hello-world\hello-world.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.004s, CPU: 0.003s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.004s, CPU: 0.004s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 4096 sample-frame blocks
```

I will look at setting up msvc2017 over the next few days if I'm unable to resolve. Thanks!

**Comment by rorywalsh** [comment] 2018-05-02 11:43
Can you run -odac99 after the csd file name?

csound helloworld.csd -odac99

When i run it I get:

C:\Users\rory\Desktop>csound "Hello World.csd" -odac99
0dBFS level = 32768.0
--Csound version 6.10 (double samples) Jan 31 2018
[commit: f5bcd83a9799536980d0f674bb7525f45f800490]
libsndfile-1.0.29pre1
UnifiedCSD:  Hello World.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.006s, CPU: 0.006s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.007s, CPU: 0.008s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 4096 sample-frame blocks
PortAudio V19.6.0-devel, revision unknown
   0: dac0 (Microsoft Sound Mapper - Output [MME])
   1: dac1 (Speakers (2- High Definition Au [MME])
   2: dac2 (Primary Sound Driver [Windows DirectSound])
   3: dac3 (Speakers (2- High Definition Audio Device) [Windows DirectSoun)
   4: dac4 (ASIO4ALL v2 [ASIO])
   5: dac5 (Speakers (2- High Definition Audio Device) [Windows WASAPI])
   6: dac6 (Speakers (HD Audio Speaker) [Windows WDM-KS])
 *** PortAudio: error: output device number 99 is out of range
closing device
Failed to initialise real time audio output
inactive allocs returned to freespace
end of score.              overall amps:      0.0
           overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.215s, CPU: 0.215s

C:\Users\rory\Desktop>

You should see something similar.

**Comment by allforabit** [comment] 2018-05-02 13:41
![capture](https://user-images.githubusercontent.com/537189/39526457-b2cfcc4e-4e16-11e8-8bfb-94294f23d1ce.PNG)
I've attached a screenshot of running that exact command (with the filename corrected). Hopefully this is of help.

**Comment by rorywalsh** [comment] 2018-05-03 09:34
Looks like the issue might be with portaudio? I had a typo in my previous message regarding the windows drivers, can you try this instead?

`csound hello-world.csd -+rtaudio=winmm -odac99`

If that doesn't crash, try selecting the appropriate device number and putting that after the -odac

**Comment by allforabit** [comment] 2018-05-03 09:55
Oh that worked and with the same default dac. Thanks very much for that. The port audio issue then is likely to be somehow related to a local machine issue. That resolves the issue for me, I'll just use the `-+rtaudio=winmm -odac` command line option. If I manage to get a build of csound setup I'll report back if I can find any more specifics of the the port audio issue. Thanks again!

**Comment by rorywalsh** [comment] 2018-05-03 11:39
Looks like a portaudio issue then. You might do a search for portaudio .dlls on your system. It looks like Csound might be picking up a rogue one somewhere. You could also try putting Csound at the front of the system path to help make sure it looks for its own lib dlls first. Another thing you might try is to run Csound with [DepWalker](http://www.dependencywalker.com/) It will list the dlls Csound tries to load. That should identify which version of portaudio.dll is causing the problem. My guess is there might be one in system32, you could try removing that and seeing what happens.

**Comment by joachimheintz** [comment] 2018-05-03 17:12
you should also be able to set this in CsounQt in Configure > Run > RT 
Audio Module.
best -
	joachim

**Closed** 2019-05-13 19:31 UTC
