### ISSUE TITLE
chuap manual example does not work - parser error?

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#327] opened 2020-06-27 14:04 UTC
line 45:
>>>aI3, aV2, aV1 chuap <<<
Unexpected untyped word aV1 when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by gesellkammer** [comment] 2020-06-27 14:14
I can't reproduce, I get very nice chaotic sounds. Please check the presence of the chuap opcode:

`csound -z1 2>&1 | grep chuap`

**Comment by csounder** [comment] 2020-06-27 14:30
Thanks Eduardo, I will try it from the terminal.

The thing is - I am working with two versions of Csound on my system - the
latest "developer" version that I "brew install" and runs from the
terminal.  And the distribution version that one installs with the .dmg
file.

I would appreciate your help, and advice (and maybe others could use it
too) for how to get CsoundQt to point to a "brew installed Csound" so that
one could use the latest developer build with CsoundQt.

I can share with you what I try to do - such as changing the
Csound Executable in your environment tab to /usr/local/bin/csound (which
is the version that runs from the terminal - the brew install --HEAD csound
version,
but CsoundQt crashes when I do this.

I try your "recommended" button - and it does write in full paths for the
OPCODE6DIR64 and INCDIR but this crashes CsoundQt as well.

There are more details that I could report if you are interested and
available to help get this working.
- it would be huge for all my students (especially those leaning toward
development)

I am figuring that the brew install opcode dir is not in the same location
as the Csound.dmg install opcode dir and a few other things too perhaps.

Can't wait to check out, use, show all your plugins - it is exciting that
you have ported so many cool opcodes and things from PD and Supercollider!
Huge really.  (I would love them to just be in the release of Csound
itself, but I am happy to get the plugin system working too.)

-dB

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by csounder** [comment] 2020-06-27 14:37
Thanks for this print and grep command

I can report that it does not find the chuap opcode, but it does find a lot
of things if I replace chuap with oscil

From the terminal, I am running:

--Csound version 6.14 (double samples) Jan 26 2020

[commit: 0ce67f7c105ed2aee98d0e7f43558d62357c769b]

libsndfile-1.0.28


From CsoundQt, the run of the chuap opcode did report that it could not
find certain libraries, but then when I used the "recommend" button - it no
longer complains about not finding them.



*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by csounder** [comment] 2020-06-27 14:46
But... it does tell me that it can't find the portaudio libraries anymore

In a dialog box I read this:


No real-time audio modules were found.

Make sure OPCODE6DIR64 is set properly in your systemor the configuration
dialog.



and in the console, I read this:




For INCDIR, recommend puts in the following path:

/Users/dB/Library/Application Support/csound6/udos


For OPCOD6DIR64, recommend puts in the following path:

/usr/local/lib/csound/plugins64-6.0:/Users/dB/Library/Application
Support/csound6/plugins64


Csound Executable is:

csound


Python Executable is:

python


RT Audio Module = null


The version of CsoundQt is:

Version 0.9.8-rc3. (Tarmo sent this along a few weeks ago and I have been
having my students use it too)




*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by gesellkammer** [comment] 2020-06-27 14:53
If the chuap opcode is not found, then it means that it was not built for your system. If you built from sources there is a cake option to enable different plugins (use cmake-gui if you are unsure). Otherwise, stick to the released csound version, which probably has chuap enabled. 

Using multiple installations of csound is not something we can support. If you do that it means that you are proficient enough to deal with the consequences. Note that csoundqt just asks the os for the csound library so there is no setting you can modify in csoundqt to "point" it at your csound installation. The csound path setting in the environment tag in csoundqt refers exclusively to the csound binary used when running csound via the terminal. 

I am closing this issue as this seems unrelated to csoundqt.

**Closed by gesellkammer** 2020-06-27 14:53 UTC
