### ISSUE TITLE
BUG copy&paste text in editor is failing after play sound

### ISSUE THREAD

**Issue by Parlazo** [CsoundQt/CsoundQt#322] opened 2020-06-16 20:47 UTC
yesterday i did send this bug report to the csound hub... they did point me to here and said its probably a csoundQT issue and not a csound issue so i try here....

the copy and paste function is failing after i play a sound in the qt editor by csound 6.14 which is have downloaded just yesterday on windows 7
it did work well but after some howers i did try this FLTK widget thing and since then i have this bug
restart does not solve the problem and cleaning the csd file from FLTK stuff by commenting it all out does not help
but before i did try this it did work and since i did try it copy and paste does not work even if i deactivate FLTK by commenting and restart qt editor
in the widget panel i have just an osciloscope and i would like to keep at least this
the FLTK code stuff is actually not so interesting to me as i am new to csound
i saw postings around the net about this problem date to 2009 and others
a solution should be to deactivate widgets.dll and virtual.dll in the csound plugin folder
but as i said i would like to keep the osciloskope in the widgets panel and be able to use copy and paste in the editor at the same time
some where i saw a posting and they said its a solved problem
they said csound and this FLTK stuff is using the clipboard at the same time and this is not possible in windows and they had fixed it in a early version of csound
but now i have the exactly same error in 2020
please if possible refix this problem
thank you any way

**Comment by tarmoj** [comment] 2020-06-17 13:24
Hi,

Yes, it was a very nasty and well hidden issue.
I am not sure, if I understand, do you need to use some of the FLTK widgets
along with CsoundQt's widgets?
You write that "in the widget panel i have just an osciloscope and i would
like to keep at least this". Can you use CsoundQt's Scope widget instead? I
guess your best bet is to avoid FLTK, if you need something special, you
can write it in html (since v0.9.7), too.
What happens if you uncheck "Enable FLTK Widgets" from Configure->Widgets?
Does it bring the copy-paste back?
Otherwise copy and paste has been reported to work on Windows.

tarmo

Kontakt Parlazo (<notifications@github.com>) kirjutas kuupäeval T, 16.
juuni 2020 kell 23:48:

**Comment by Parlazo** [comment] 2020-06-17 20:59
I use csoundQT on windows 7 64bit
All did work well... then i have read about this FLTK widgets in the help files an i tested it... the widget did open in a seperate window and every thing did look ok
but since then copy/paste does not work at all
i have the osciloscope in the csoundQT panel and i think its not FLTK
but what ever i try copy/paste functionality is gone
i also unchecked the FLTK Widgets in the options config panel and did a csoundQT restart, but still after playing the file once the copy/paste function is gone
i can copy some thing in a other editor and paste it to the csoundQT editor but i can not copy any thing from the csoundQT editor and paste it any where and also not in the csoundQT editor it self
it all works if i do not play any thing but after i play any thing copy paste is gone
i did noticealso an other strange thing but i can not clearly see the logic behind it... some times the keyboard shortcuts get totally lost and i have to restore them to default but still after a reset to default it does not bring back copy/paste until i restart csoundQT and just to the point where i play some thing.. and the newest thing that happens in the menu or toolbar... all button pictures or icons are gone except of the html button or in the menu the html icon
in the options...
enable widgets is checked
save widgets in csd file is unckecked
show widgets on play is checked
show tooltips for widgets is checked
enable FLTK is unchecked
run FLTK csds in terminal is always grayed out... when i enabel or disabel FLTK this option keeps unclickable
store old widgets format is unchecked
open properties when cratin a widget is checked
widgets are an independent window is unchecked
csoundQT is version 0.9.7
csound is vrsion 6.14.0 64bit
windows is 7pro 64bit

maybe there is some setting that got checked when i did try the FLTK thing which does not get unchecked when i disable the FLTK thing?
and maybe this some how affects the shortcut settings which get lost from time to time but where i actually cant see a logical pattern to reproduce it... it just happens some times some how but not always
and why the button pictures and icons got lost except of the html button and icon... i can only guess... i did star to use csoundQT in default english but once i did try it in german and then again in english but the button pictures and icons are lost even after restarting csoundQT

is there a simple way to just reset every thing to default?
i did download csoundQT from https://csound.com/download.html 64bit Full Installer v6.14.0

**Comment by joachimheintz** [comment] 2020-06-18 07:20
can you try Help > Reset Preferences ?

**Comment by Parlazo** [comment] 2020-06-19 10:42
Now i did "Help > Reset Preferences"
this gave me back the button pictures and icons in the menu after a restart of csoundQT
but the copy/paste problem after playing a sound remains
i also did this "Help > Reset Preferences" thing and removed the whoe FLTK stuff from the file which was already commented out and i did copy the whole code before playing a sound and opened a new file and paste the whole code to a new file but without the FLTK part and the problem remains, after playing the file copy&paste does not work
and i also noticed after the "Help > Reset Preferences" thing, while the button pictures and icons came back and in the option it said csoundQT uses english language the menu text and button text was/is still in german language even if the options say it is english after the reset

so some how i suspect csoundQT to reset the settings but it does not read them properly out, at least the language settings... i mean if it says english after a restart and the display text is german some thing went wrong... and maybe this affects also the FLTK settings somehow which i disable but may they are still enabled... also the phenomenon where the shortcut settings got/get lost is maybe an effect of the same issue

and the copy paste issue in the editor is maybe because the FLTK settings as i read some where before i came here... there they said it is because csoundQT and FLTK seem to use the clipboard at the same time and this is not possible in windows... i dont understand how FLTK uses the clipboard wehen i am editing some thing in the csoundQT editor.. but if so may a solution would be to delay the copy paste functions for a millisecond in csoundQT or FLTK

what i found about this issue is...
https://github.com/CsoundQt/CsoundQt/issues/239
here they talk about the clipboard problem on windows when csoundQT and FLTK use it at the exactly same time
i did not try to delete dll's because the issue there is from around 2017 and i think it is maybe already fixed or an new issue
now when i read it again they talk also about an old component and about reinstall.. i will try this next.. but i installed csoundQT last week from the main site and i think this should get fixed.. by removing old components or by doing magical tricks some how

https://csoundqt.github.io/release095.html
here they say the nasty copy paste problem got fixed, but i have an other experience

https://sourceforge.net/p/qutecsound/mailman/message/24276268/
here they also talk about the plugin folder and the widgets.dll and virtual.dll but i dont know how this will affect the virtual keyboard.. of course i want to use this too and i also dont know how this affects the csoundQT widgets which i also like to use
they also talk about a ctrl-s problem... this seems to me very clear to be the same as i get when csoundQT looses all the shortcut settings out of nothing... first i suspected this as the cause of loosing copy/paste but resetting the shortcuts to default did work but after playing a sound csoundQT forgot how to copy/paste

i hope if there is a way to solve this problem or problems it will be soon in the installer on the main site, to new users this may could look a bit shocking and will freak them away

how ever i will keep trying and do not give up

The reason why i did try to use FLTK widgets was because i could code them in the editor
the reason why i dont like the is because the copy/paste problem
but what i really would like is at least the csoundQT panel widgets if this is possible without FLTK

so maybe this is now a huge bug report... but i really hope all this stuff can get solved and thats why i try to provide you any information i can to make things better

thanks any way for all the hard work... thank you thank you

**Comment by Parlazo** [comment] 2020-06-19 12:50
i did a uninstall
clean every thing i found in the program files folder and in the programs folder and in the registry under local user software
then redownload and reinstall
then open the csd file in notepad and copy the part before <bsbPanel> to a new csd file
i did deactivate in the options all FLTK stuff
in the settings was written the display language is english but every thing was still written in german after the reinstall
after playing the sound copy/paste was gone again... i cant copy paste in the csoundQT editor

**Comment by tarmoj** [comment] 2020-06-19 13:03
Thanks for so thorough testing!

The problem is I am not on Windows myself and have limited possibilities to
test and build.
Would you please try one more thing - please move widgets.dll and
virtual.dll away from Csound's folder and see if it makes any difference.

The language problem is very strange, though...

tarmo


Kontakt Parlazo (<notifications@github.com>) kirjutas kuupäeval R, 19.
juuni 2020 kell 15:50:

**Comment by Parlazo** [comment] 2020-06-19 13:46
i did rename widgets.dll and virtual.dll to *.dll_
this does in fact fix the copy paste bug
and the csoundQT internal or own widgets in the panel do still work... at least the oscilloscope

but i also found...
if i install csound it seems to use the windows system language (german) as display language but in the settings the csound default language (english) is shown
and if i save the settings as they are, all icons and button pictures are gone except of the HTML icon and button, even if i do not change any thing in the settings
this also does delete all shortcuts
then i can reset all the settings from the helt menu and all icons and button pictures come back
but always the only button and icon which is not affected and is always visible is the html icon and button which always keeps its picture and icon in the menu

**Comment by Parlazo** [comment] 2020-06-19 14:08
![button_and_icons_and_shortcuts_gone_after_save_language_settings](https://user-images.githubusercontent.com/66982240/85140810-18b21400-b246-11ea-8078-1188b29763ef.gif)
here a picture of gone buttons and icons after i save the settings and no language brings them back and shortcuts will also get lost... so this is a second issue of why copy paste does not work

to make copy paste work...
rename virtual.dll and widgets.dll to virtual.bak and widgets.old (or any thing but not *.dll)
if you save some settings all shortcut settings get lost and you have to reset the default shortcut settings
to bring the icons and button pictures back you have to reset the whole csoundQT settings and this will work until you change any settings

so if you save any csoundQT settings you can loose the button pictures and icons except of the HTML5 button and icon and you loose the shortcut settings (at least if you change the language)

**Comment by Parlazo** [comment] 2020-06-19 16:12
OK i found this
virtual.dll and widgets.dll is the enemy to copy paste once you have run a file
an similar but other problem is, if you change the language from what ever is default to any language and back to english, this will erase all keyboard shortcuts and so copy paste or ctrl-s or any shortcut will not work any more
both problems can affect the copy paste functionality but they are different problems

may thats the reason why they https://sourceforge.net/p/qutecsound/mailman/message/24276268/ also talk about ctrl-s because the lost shortcut keys and this i also found and filed here as a seperate issue not related to the two dlls https://github.com/CsoundQt/CsoundQt/issues/324

i hope both bug reports can help to clear the issue and to fix it
it is maybe confusing because both issues create the same symptom but root in an other cause

**Comment by tarmoj** [comment] 2020-06-26 09:03
Hi,

I tried on  Windows 10, CsoundQt 0.9.8.
 I can confirm that if you run a csd with fltk, after that copy-paste does not work, indeed. 
But after restarting CsoundQt it is ok again. 
Otherwise copy-paste works as expected, also after playing some file. No problem with icons getting lost did not happen for me.

tarmo

**Comment by ReinerZorn** [comment] 2020-09-17 07:18
Hi,
just to confirm that for Windows 10 Pro / CsoundQT 0.9.8.1 / Csound 6.15 the bug still exists. For me it was suffcient to rename widgets.dll. (BTW, I did a complete re-install as suggested somewhere else and it did **not** help.) Still having virtual.dll is nice because sometimes I don't want to have my MIDI keyboard on my desk just to test something. So I often use the virtual keyboard and also want to do it indepently of CsoundQT. Still I think this issue should be fixed because it took me several hours to find this workaround.
Reiner

**Comment by bernardgeyer** [comment] 2020-10-27 11:47
Hi

I use CsoundQT 0.9.8.1 on Windows 10

After pressing the "Run Csound" button, copy/paste doesn't work (even if I don't use any sound in my .csd.
If there is already something in the clipboard, it will be pasted instead of what I expected.

After pressing the "Stop" button, , copy/paste works again.

The fact that "Enable FLTK" and "Run FLTK csds in Terminal are checked doesn't change anything.

But ... when "Allow simultaneous play" is checked, copy/paste works anywhere without problem.

**Closed** 2024-01-04 22:07 UTC
